### PR TITLE
Feature/fix frozen strings

### PR DESCRIPTION
**Pull request by prtngn**
Hi. I have a problem with frozen strings. This is PR fix it.

### CODE REVIEW

**Comment by janfri** [comment]
On which Ruby version does it not work?

**Comment by prtngn** [comment]
> On which Ruby version does it not work?

Ruby is 3.1.1. This problem occurs when the global `Frozen Litteral Strings` flag is set at the project level.

**Comment by prtngn** [comment]
And this PR is not full ) I still need to improve it.

**Comment by prtngn** [comment]
Yes, `# frozen_string_literal: false` one of the solutions to the problem

**Pull request merged**
